### ISSUE TITLE
Результаты код-ревью

### ISSUE THREAD

**Issue by gsomix** [SamaraITCommunity/sitc-vk-parser#2]
Привет! Сделал небольше код-ревью по просьбе @humb1t.

1. На данный момент сервис хранит свое состояние (значение `lastCheckTime`) только в оперативной памяти. Данное значение инициализируется временной отметкой на момент запуска сервиса. Если сервис "упадет", и его перезапустят через некоторое время, то все новые посты из VK, появившиеся за этот период, не будут пересланы.

1. Обработка ошибок от сторонних сервисов примитивная — вывод сообщения об ошибке в консоль. При этом отсутствует очередь постов с состоянием их обработки (например, удачно или неудачно отправлено в Telegram). Это ведет к тому, что при любой ошибке, не будет возможности переслать "неудачный" пост заново, когда сторонний сервис начнет работать.

1. В дополнение к предыдущему — сервис не отслеживает состояние сторонних сервисов, и в случае их недоступности все равно будет пытаться переслать посты.

1. Я плохо разбираюсь в асинхронности в NodeJS. Данный сервис обрабатывает посты и пересылает их асинхронно? Нет будет ли проблемы с тем, что текст и приложения отправляются двумя отдельными вызовами? Не перемешаются ли они во времени? :)

1. Было бы круто, если бы текст сообщений для пересылки приложений задавался не в коде, а в отдельных шаблонах.

1. Обрабатывать приложения в постах лучше (как для читабельности, так и для производительности) с помощью одного `forEach`+`switch`, чем через вызов нескольких `filter`+`forEach`.

Спасибо!

**Comment by gsomix** [comment]
сс @fax1ty

**Comment by fax1ty** [comment]
@gsomix 
~~1. Пофикшу в ближайшее время~~

~~2 и 3. Не поудмал об этом, ибо не было в ТЗ. Да и срок был всего день. Попытаюсь реализовать некое подобие очереди.~~

4. Любые запросы параллельны. Всё выполнится по мере времени и вернёт ответ в resolve часть Promise

5. Поясните, пожалуйста, что Вы конкретно имели в виду? О каких сообщениях идёт речь?

~~6. Да, понял, что сделал дичь. Перепишу в ближайшее время~~

**Comment by humb1t** [comment]
@fax1ty @gsomix Спасибо - перенесу 5 пункт в отдельную issue.
