### ISSUE TITLE
Extract messages into template.

### ISSUE THREAD

**Issue by humb1t** [SamaraITCommunity/sitc-vk-parser#3]
> Было бы круто, если бы текст сообщений для пересылки приложений задавался не в коде, а в отдельных шаблонах.

Follow-up from #2

**Comment by fax1ty** [comment]
Вопрос тот же, что и в прошлой ишью - как эти шаблоны должны выглядеть

**Comment by fax1ty** [comment]
https://github.com/SamaraITCommunity/sitc-vk-parser/pull/6 Должен решить это.
