### ISSUE TITLE
Underline (_) is parsing as italic in Telegram

### ISSUE THREAD

**Issue by Hermesiss** [SamaraITCommunity/sitc-vk-parser#7]
Original: `#sitc_game_jam`
Tg: #sitc _game_ jam

**Comment by fax1ty** [comment]
@Hermesiss Можно более конкретный юз кейс?

Это можно пофиксить убрав parse_mode. Подробнее: https://tlgrm.ru/docs/bots/api#sendmessage
https://github.com/SamaraITCommunity/sitc-vk-parser/blob/0b5e0c8baf11b2f5a692efd4c2cb737eb7835f4b/libs/api/telegram_api.ts#L31
Не уверен, использую ли я где-то возможности Markdown в боте, но если они всё же используются, то тогда такое сообщение будет отправлено, как обычный текст.

**Comment by fax1ty** [comment]
Ещё можно использовать `\` перед `_` в хэш-тегах. Напишу фикс в ближайшее время. Придётся сканировать каждое сообщения на теги

**Comment by fax1ty** [comment]
Исправлено в https://github.com/SamaraITCommunity/sitc-vk-parser/pull/6, но нужны тесты
